# Generated by Django 4.2.5 on 2023-09-17 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('popular', models.BooleanField(default=False)),
                ('family_friendly', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(to='tourism.category')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=50),
        ),
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='location_pics')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_images', to='tourism.location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='images',
            field=models.ManyToManyField(related_name='locations', to='tourism.locationimage'),
        ),
    ]
