# Generated by Django 4.2.5 on 2023-09-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_category_location_user_verified_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
