# Generated by Django 4.2.5 on 2023-09-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_location_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='location',
            name='categories',
            field=models.CharField(choices=[('view', 'View'), ('food', 'Food'), ('architecture', 'Architecture')], max_length=30, null=True),
        ),
    ]
