# Generated by Django 4.2.5 on 2023-09-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0006_remove_location_categories_delete_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationimage',
            name='location',
        ),
    ]
