# Generated by Django 4.2.5 on 2023-09-18 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_remove_locationimage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationimage',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_images', to='tourism.location'),
        ),
    ]
