# Generated by Django 4.2.5 on 2023-09-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0009_location_latitude_location_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
