# Generated by Django 4.2.5 on 2023-09-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0010_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='categories',
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(choices=[('Adrar', 'Adrar'), ('Aflou', 'Aflou'), ('Aïn Témouchent', 'Aïn Témouchent'), ('Akbou', 'Akbou'), ('Alger', 'Algiers'), ('Annaba', 'Annaba'), ('Batna', 'Batna'), ('Béchar', 'Béchar'), ('Béjaïa', 'Béjaïa'), ('Béni Abbès', 'Béni Abbès'), ('Birkhadem', 'Birkhadem'), ('Blida', 'Blida'), ('Bordj Bou Arreridj', 'Bordj Bou Arreridj'), ('Bou Saâda', 'Bou Saâda'), ('Bouira', 'Bouira'), ('Boumerdès', 'Boumerdès'), ('Chlef', 'Chlef'), ('Constantine', 'Constantine'), ('Djelfa', 'Djelfa'), ('El Eulma', 'El Eulma'), ('El Harrach', 'El Harrach'), ('El Khroub', 'El Khroub'), ('El Oued', 'El Oued'), ('El Tarf', 'El Tarf'), ('Guelma', 'Guelma'), ('Jijel', 'Jijel'), ('Khenchela', 'Khenchela'), ('Laghouat', 'Laghouat'), ("M'sila", "M'sila"), ('Médéa', 'Médéa'), ('Mostaganem', 'Mostaganem'), ('Oran', 'Oran'), ('Ouargla', 'Ouargla'), ('Relizane', 'Relizane'), ('Sétif', 'Sétif'), ('Sidi Bel Abbès', 'Sidi Bel Abbès'), ('Skikda', 'Skikda'), ('Tamanrasset', 'Tamanrasset'), ('Tébessa', 'Tébessa'), ('Tiaret', 'Tiaret'), ('Timimoun', 'Timimoun'), ('Tipasa', 'Tipasa'), ('Tizi Ouzou', 'Tizi Ouzou'), ('Tlemcen', 'Tlemcen')], default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='location',
            name='places',
            field=models.CharField(choices=[('Beach', 'beach'), ('Park', 'park'), ('Forest', 'forest'), ('Lake', 'lake'), ('City', 'city'), ('Restaurant', 'restaurant')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='weather',
            field=models.CharField(choices=[('Cold', 'cold'), ('Warm', 'warm')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='family_friendly',
            field=models.BooleanField(default=False),
        ),
    ]
