# Generated by Django 4.2.5 on 2023-09-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0011_remove_location_categories_location_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='places',
            field=models.CharField(choices=[('Beach', 'Beach'), ('Park', 'Park'), ('Forest', 'Forest'), ('Lake', 'Lake'), ('City', 'City'), ('Restaurant', 'Restaurant')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='location',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
