# Generated by Django 4.2.5 on 2023-09-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0012_alter_location_places_alter_location_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='summary',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
