# Generated by Django 4.2.5 on 2023-09-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0013_location_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='summary',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
