# Generated by Django 4.2.5 on 2023-09-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0016_user_city_alter_user_address_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='verification',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='city',
            field=models.CharField(choices=[('Adrar', 'Adrar'), ('Aflou', 'Aflou'), ('Aïn Témouchent', 'Aïn Témouchent'), ('Akbou', 'Akbou'), ('Alger', 'Algiers'), ('Annaba', 'Annaba'), ('Batna', 'Batna'), ('Béchar', 'Béchar'), ('Béjaïa', 'Béjaïa'), ('Béni Abbès', 'Béni Abbès'), ('Birkhadem', 'Birkhadem'), ('Blida', 'Blida'), ('Bordj Bou Arreridj', 'Bordj Bou Arreridj'), ('Bou Saâda', 'Bou Saâda'), ('Bouira', 'Bouira'), ('Boumerdès', 'Boumerdès'), ('Chlef', 'Chlef'), ('Constantine', 'Constantine'), ('Djelfa', 'Djelfa'), ('El Eulma', 'El Eulma'), ('El Harrach', 'El Harrach'), ('El Khroub', 'El Khroub'), ('El Oued', 'El Oued'), ('El Tarf', 'El Tarf'), ('Guelma', 'Guelma'), ('Jijel', 'Jijel'), ('Khenchela', 'Khenchela'), ('Laghouat', 'Laghouat'), ("M'sila", "M'sila"), ('Médéa', 'Médéa'), ('Mostaganem', 'Mostaganem'), ('Oran', 'Oran'), ('Ouargla', 'Ouargla'), ('Relizane', 'Relizane'), ('Sétif', 'Sétif'), ('Sidi Bel Abbès', 'Sidi Bel Abbès'), ('Skikda', 'Skikda'), ('Tamanrasset', 'Tamanrasset'), ('Tébessa', 'Tébessa'), ('Tiaret', 'Tiaret'), ('Timimoun', 'Timimoun'), ('Tipasa', 'Tipasa'), ('Tizi Ouzou', 'Tizi Ouzou'), ('Tlemcen', 'Tlemcen')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
