# Generated by Django 4.2.5 on 2023-09-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0017_remove_user_address_remove_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='state',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Refused', 'Refused')], default='Pending', max_length=10),
        ),
    ]
