# Generated by Django 4.2.5 on 2023-10-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0020_remove_location_rating_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='proof',
            field=models.ImageField(null=True, upload_to='ratingProof_pics'),
        ),
    ]
