# Generated by Django 4.2.5 on 2023-10-11 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0021_rating_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
