# Generated by Django 4.2.5 on 2023-10-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0022_rating_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='Location_rating',
            new_name='location_rating',
        ),
    ]
